<script type="text/javascript">
(function() {
    var sc = document.createElement('script'); sc.type = 'text/javascript'; sc.async = true;
    sc.src = ('https:' == document.location.protocol ? 'https://zefzhat.appspot.com' : 'http://www.livezhat.com') + '/code/<?php echo $this->getCustomerKey() ?>/<?php echo $this->getZhatKey() ?>';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sc, s);
})();
</script>